#ifndef USER_MANAGEMENT_GUARD__H 
#define USER_MANAGEMENT_GUARD__H

#include <stdio.h>
#define TYPE_USER		0
#define TYPE_LIBRARIAN	1
#define MAX_MUN_USER	1000
#define MAX_CHAR		16

struct User {
	char username[MAX_CHAR]; //user name
	char password[MAX_CHAR]; //password
	unsigned int type; //user type
};

struct UserArray {
	struct User* array; // pointer to array of struct User.
	unsigned int length; // number of elements in the struct User
};


//saves the database of users in the specified file
//returns 0 if users were stored correctly, or an error code otherwise
int store_users(FILE *file);

//loads the database of users from the specified file
//the file must have been generated by a previous call to store_users()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_users(FILE *file);

//register a user to the database
//returns 0 if the user could be registered, or an error code otherwise
int user_register(struct User user);

//removes a user from the database
//returns user type if the user login successful, or -1 otherwise.
int user_login(struct User user);

//search a user from the database
//returns index of the user in array if the user could be found, or an error code otherwise.
int search_user(const char* user_name);

#endif
